/* Convert LED sign font to C, so it doesn't have to be loaded at runtime. */
/* Copyright 2017 Boris Gjenero. Released under the MIT license. */

#include <stdio.h>
#include "ledsign.h"

static sign_font_t font;

int main(int argc, char **argv) {
    int i;

    if (argc != 2) {
        fprintf(stderr, "USAGE %s in_font\n", argv[0]);
        return -1;
    }

    if (sign_loadfont(argv[1], &font) != 0) {
        fprintf(stderr, "Error loading font\n");
        return -1;
    }

    printf("/* This file was automatically generated by %s from %s */\n\n",
           argv[0], argv[1]);

    printf("static const sign_font_t font1 = {\n   {\n       ");
    for (i = 0; i < sizeof(font.data); i++) {
        if ((i & 7) == 0 && i > 0) printf("\n       ");
        printf(" 0x%02x,", font.data[i]);
    }
    printf("\n    }, %i, %i,\n};\n", font.height, font.width);
    return 0;
}
